import { useStuecklisteStore } from '../stores/stueckliste'

const formatCurrency = value => new Intl.NumberFormat('de-DE', {
  style: 'currency', currency: 'EUR', minimumFractionDigits: 2, maximumFractionDigits: 2,
}).format(value)

const stockLabels = {
  in_stock: 'Verfügbar',
  low_stock: 'Niedrig',
  out_of_stock: 'Nicht vorrätig',
}

export async function exportBOMAnalysisPDF(displayedItems) {
  const store = useStuecklisteStore()
  const bomItems = displayedItems ?? store.enriched
  const totalCost = bomItems.reduce((sum, item) => sum + item.totalCost, 0)
  const mostExpensive = bomItems.reduce((current, item) =>
    !current || item.totalCost > current.totalCost ? item : current,
  null)
  const avgLeadTime = Math.round(bomItems.reduce((sum, item) => sum + item.leadTime, 0) / bomItems.length)
  const supplierCount = new Set(bomItems.map(item => item.supplier)).size
  const stockSummary = {
    in_stock: bomItems.filter(item => item.stock === 'in_stock').length,
    low_stock: bomItems.filter(item => item.stock === 'low_stock').length,
    out_of_stock: bomItems.filter(item => item.stock === 'out_of_stock').length,
  }
  const { default: jsPDF } = await import('jspdf')
  const { default: autoTable } = await import('jspdf-autotable')
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const createdAt = new Date().toLocaleString('de-DE')

  doc.setFillColor(49, 46, 129)
  doc.rect(0, 0, 210, 30, 'F')
  doc.setTextColor(255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(17)
  doc.text('Bill of Materials (BOM) Report', 14, 13)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text(`Date and time: ${createdAt}`, 14, 22)
  doc.text('Product: Autonomer Lagerroboter AR-200', 196, 22, { align: 'right' })

  autoTable(doc, {
    startY: 37,
    head: [['Total Cost', 'Most Expensive Component', 'Average Delivery Time', 'Number of Suppliers']],
    body: [[
      formatCurrency(totalCost),
      mostExpensive.name,
      `${avgLeadTime} days`,
      supplierCount,
    ]],
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [76, 29, 149], textColor: 255, fontStyle: 'bold' },
  })

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(30, 41, 59)
  doc.text('BOM Table', 14, doc.lastAutoTable.finalY + 11)

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 15,
    head: [['Position', 'Component Name', 'Group', 'Quantity', 'Unit Price (€)', 'Total Price (€)', 'Supplier', 'Inventory Status', 'Delivery Time']],
    body: bomItems.map(item => [
      item.id, item.name, item.group, item.qty,
      formatCurrency(item.unitCost), formatCurrency(item.totalCost),
      item.supplier, stockLabels[item.stock], `${item.leadTime} days`,
    ]),
    styles: { fontSize: 6.3, cellPadding: 1.8, overflow: 'linebreak' },
    headStyles: { fillColor: [76, 29, 149], textColor: 255, fontStyle: 'bold', fontSize: 6.3 },
    alternateRowStyles: { fillColor: [248, 247, 255] },
    columnStyles: { 3: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' }, 8: { halign: 'right' } },
  })

  const summaryY = doc.lastAutoTable.finalY + 11
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(30, 41, 59)
  doc.text('Summary', 14, summaryY)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  const summary = [
    `Total Components: ${bomItems.length}`,
    `Total Cost: ${formatCurrency(totalCost)}`,
    `Available Components: ${stockSummary.in_stock}`,
    `Low Stock Components: ${stockSummary.low_stock}`,
    `Out-of-Stock Components: ${stockSummary.out_of_stock}`,
  ]
  summary.forEach((line, index) => doc.text(line, 14, summaryY + 7 + index * 6))

  const pages = doc.internal.getNumberOfPages()
  for (let page = 1; page <= pages; page++) {
    doc.setPage(page)
    doc.setFontSize(8)
    doc.setTextColor(120)
    doc.text('Generated by Logistics Dashboard', 14, 289)
    doc.text(`Page ${page} of ${pages}`, 196, 289, { align: 'right' })
  }

  doc.save('bom-analysis-report.pdf')
}
