import { useMakeOrBuyStore } from '../stores/makeorbuy'

const formatCurrency = value => new Intl.NumberFormat('de-DE', {
  style: 'currency', currency: 'EUR', maximumFractionDigits: 0,
}).format(value)

function supplierStatus(supplier, store) {
  const labels = []
  if (supplier.id === store.recommendedSupplier.id) labels.push('Recommended')
  if (supplier.id === store.bestPriceSupplier.id) labels.push('Lowest Price')
  if (supplier.id === store.fastestSupplier.id) labels.push('Fastest Delivery')
  return labels.join(' · ') || 'Qualified'
}

export async function exportSupplierComparisonPDF() {
  const store = useMakeOrBuyStore()
  const { default: jsPDF } = await import('jspdf')
  const { default: autoTable } = await import('jspdf-autotable')
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const createdAt = new Date().toLocaleString('de-DE')

  doc.setFillColor(15, 23, 42)
  doc.rect(0, 0, 210, 30, 'F')
  doc.setTextColor(255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(17)
  doc.text('Supplier Comparison Report', 14, 13)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text(`Date and time: ${createdAt}`, 14, 22)
  doc.text(`Product: ${store.selectedProduct.name}`, 196, 22, { align: 'right' })

  autoTable(doc, {
    startY: 38,
    head: [['Supplier', 'Price (€)', 'Delivery Time (days)', 'Quality Rating', 'Status']],
    body: store.suppliers.map(supplier => [
      supplier.name,
      formatCurrency(supplier.price),
      supplier.leadTime,
      `${supplier.quality}/10`,
      supplierStatus(supplier, store),
    ]),
    styles: { fontSize: 9, cellPadding: 3.5 },
    headStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [242, 247, 255] },
    columnStyles: { 1: { halign: 'right' }, 2: { halign: 'right' }, 3: { halign: 'center' } },
  })

  const summaryY = doc.lastAutoTable.finalY + 12
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(30, 41, 59)
  doc.text('Summary', 14, summaryY)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(`Recommended Supplier: ${store.recommendedSupplier.name}`, 14, summaryY + 8)
  doc.text(`Lowest Price Supplier: ${store.bestPriceSupplier.name} (${formatCurrency(store.bestPriceSupplier.price)})`, 14, summaryY + 15)
  doc.text(`Fastest Delivery Supplier: ${store.fastestSupplier.name} (${store.fastestSupplier.leadTime} days)`, 14, summaryY + 22)

  const pages = doc.internal.getNumberOfPages()
  for (let page = 1; page <= pages; page++) {
    doc.setPage(page)
    doc.setFontSize(8)
    doc.setTextColor(120)
    doc.text('Generated by Logistics Decision Support Dashboard', 14, 289)
    doc.text(`Page ${page} of ${pages}`, 196, 289, { align: 'right' })
  }

  doc.save('supplier-comparison-report.pdf')
}
